#!/usr/bin/env bash
# Install Nginx on server with following configurations:
#+      Listen on port 80
#+      Return a page containing "Hello World!" when querried at he root using curl GET request

sudo apt-get update
sudo apt-get install nginx nginx-common nginx-core -y

sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html > /dev/null
sudo service nginx restart
