#!/usr/bin/env bash
# configure web-02 to be identical to web-01.
#+ Configure Nginx so that its HTTP response contains
#++ a custom header (on web-01 and web-02)
#+++ The name of the custom HTTP header must be X-Served-By
#+++ The value of the custom HTTP header must be the hostname
#+++ of the server Nginx is running on

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" | sudo tee -a /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
