#!/usr/bin/env bash
# installing and configuring load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 47988-web-01 34.227.90.97:80 check
    server 47988-web-02 54.90.1.16:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
