#!/usr/bin/env bash
# on 9th iteration, display "Best school" and then "Hi" on a new line

count=0

while [ $count -ne 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
